Card 6 - Requisição API - Gráfico
viniciusrovigowarren/trilha-propulsao pull request #6
Opened 2022-09-26 15:39 UTC by viniciusrovigowarren

[Flutter] Card 6 - Request API - Graphic

### **Critério de aceitação**
- Aplicar request em todas as telas já construídas.

- Utilizar o DIO.

- Dados como: Assets(imagens), valor atual da cripto, variação do dia e dados do gráfico devem vir da api.

### **Bônus**

- Shimmer para carregamento dos dados da API

### **Preview**

https://user-images.githubusercontent.com/113137029/192320128-6088fef8-7933-4950-80a5-7d8988c3b85b.mp4

2022-09-26 16:57 UTC, CarlosTSIlva requested changes

2022-09-26 16:57 UTC, CarlosTSIlva commented on lib/details/widgets/details_body.dart
> +      return LoadingDetails(size: size);
pra q isso? de setState

2022-09-26 16:57 UTC, CarlosTSIlva commented on lib/portifolio/repository/wallet_repository.dart
> +    ];
deveria fazer um map nesse allCoins porque se n tiver a casa decimal ele vai crashar, e a casa 10 fica vazia?

2022-09-26 20:34 UTC, viniciusrovigowarren commented on lib/details/widgets/details_body.dart
> +      return LoadingDetails(size: size);
Eu usei pois, quando eu inicio o app, ele faz um get da api do histórico de preços de uma moeda, e como estou usando o provider, quando iniciar o app, vai iniciar o provider e dar um get.
Então quando eu clico em uma moeda ele vai fazer a requisição, por isso que o histórico de preços não está carregado ainda, por isso precisei do setState.

2022-09-26 20:36 UTC, viniciusrovigowarren commented on lib/portifolio/repository/wallet_repository.dart
> +    ];
Esses dados de saldo do usuários são mockados, apenas para simular algumas moedas que o usuário tenha em carteira!

2022-09-27 11:36 UTC, CarlosTSIlva approved these changes

2022-09-27 11:57 UTC, merged